site_name: XpertCorpus 文档
site_description: 轻量级大模型语料构建端到端框架
site_author: rookielittleblack
site_url: https://rookie-littleblack.github.io/XpertCorpus

# Repository
repo_name: rookie-littleblack/XpertCorpus
repo_url: https://github.com/rookie-littleblack/XpertCorpus
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 rookielittleblack

# Configuration
theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Hooks (commented out for now, can be added later)
# hooks:
#   - material/overrides/hooks/shortcodes.py
#   - material/overrides/hooks/translations.py

# Additional configuration
extra:
  status:
    new: 最近添加
    deprecated: 已弃用
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/rookie-littleblack
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/xpertcorpus/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: rookie-littleblack
      repo: XpertCorpus
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - 主页: index.md
  - 快速开始:
    - 安装指南: tutorials/getting-started/README.md
    - 基础使用: tutorials/basic-usage/README.md
    - 进阶教程: tutorials/advanced-usage/README.md
    - 最佳实践: tutorials/best-practices/README.md
  - API 文档:
    - api/README.md
    - 工具层:
      - api/utils/README.md
      - 异常处理: api/utils/xerror_handler.md
      - 日志系统: api/utils/xlogger.md
      - 配置管理: api/utils/xconfig.md
      - 存储管理: api/utils/xstorage.md
      - 工具函数: api/utils/xutils.md
    - 基础设施层:
      - api/others/README.md
      - 框架基础系统: api/others/xframework.md
      - 管道基础系统: api/others/xpipeline.md
      - 算子基类: api/others/xoperator.md
      - 注册系统: api/others/xregistry.md
      - 数据限制器: api/others/xlimitor.md
    - 微算子层:
      - api/microops/README.md
    - 算子层:
      - api/operators/README.md
    - 管道层:
      - api/pipelines/README.md
      - 文本清洗管道: api/pipelines/xcleaning_pipe.md
    - 框架层:
      - api/frameworks/README.md
      - 预训练框架: api/frameworks/xframe_pt.md
  - 架构设计:
    - architecture/README.md
    - 设计原则: architecture/design-principles.md
    - 四层架构: architecture/four-layer-arch.md
    - 注册器模式: architecture/registry-pattern.md
    - 数据流设计: architecture/data-flow.md
  - 示例:
    - examples/README.md
    - 简单示例: examples/simple-examples/README.md
    - 复杂管道: examples/complex-pipelines/README.md
    - 自定义开发: examples/custom-development/README.md
  - 开发指南:
    - development/README.md
    - 贡献指南: development/contributing.md
    - 编码规范: development/coding-standards.md
    - 测试指南: development/testing.md
    - 部署指南: development/deployment.md
  - 参考:
    - reference/README.md
    - 配置参考: reference/configuration.md
    - 错误代码: reference/error-codes.md
    - 性能优化: reference/performance.md
    - 常见问题: reference/faq.md 